<?php

//require_once "php/procer.php";

//$writer = new ThemenHandler("../../mdRDF/");
//$writer->readTTL("buchThemen.ttl");
//$writer->writeJsTreeData("gebiete", "math:Gebiet", 0);
//$writer->writeJsTreeData("methoden", "math:Methode", 0);
//$allData = json_encode($writer->jsTreeData);
?>

<!DOCTYPE html>
<html lang="de">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"/>
<!--    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">-->
    <link rel="stylesheet" type="text/css" href="metaData.css"/>
    <script type="application/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
<!--    <script type="application/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>    <script type="application/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>-->
    <script type="application/javascript" src="js/themen.js"></script>
    <script type="application/javascript" src="js/probleme.js"></script>
    <script type="application/javascript">
        $(function (){
            buildThemenTrees();
        })
    </script>
</head>
<body>
<div class="clearfix">
    <h2>Aufgaben</h2>
    <table id="problemTable">
    </table>
</div>
<div id="suchDiv" class="clearfix">
    <button id="suchButton" onclick="searchProblems('#00aa00')">Suche Aufgaben</button>
</div>
<div class="clearfix">
    <h2>Register</h2>
    <div class="treeBox">
        <h3>Gebiete</h3>
        <div id="gebieteTree"></div>
    </div>
    <div class="treeBox">
        <h3>Methoden</h3>
        <div id="methodenTree"></div>
    </div>
</div>
</body>
</html>
