<?php

require_once "php/themen.php";

$writer = new ThemenHandler("../../mdRDF/");
$writer->readTTL("buchThemen.ttl");
$writer->writeJsTreeData("gebiete", "math:Gebiet", 0);
$writer->writeJsTreeData("methoden", "math:Methode", 0);
$allData = json_encode($writer->jsTreeData);
?>

<!DOCTYPE html>
<html lang="de">
<header>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"/>
    <link rel="stylesheet" type="text/css" href="metaData.css"/>
    <script type="application/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <script type="application/javascript" src="js/themen.js"></script>
    <script type="application/javascript">
        $(function (){
            buildThemenTrees();
        })
    </script>
</header>
<body>
<div id="aufgabenTable" class="clearfix">
    <h2>Aufgaben</h2>
</div>
<div class="clearfix">
    <h2>Register</h2>
    <div class="treeBox">
        <h3>Gebiete</h3>
        <div id="gebieteTree"></div>
    </div>
    <div class="treeBox">
        <h3>Methoden</h3>
        <div id="methodenTree"></div>
    </div>
</div>
</body>
</html>
