<?php

require_once "themen.php";

$writer = new ThemenHandler("../../mdRDF/");
$writer->readTTL("buchThemen.ttl");
$writer->writeJsTreeData("math:Gebiet", 0);
$gebieteData = json_encode($writer->jsTreeData);
$writer->clearJsTreeData();
$writer->writeJsTreeData("math:Methode", 0);
$methodenData = json_encode($writer->jsTreeData);
?>

<!DOCTYPE html>
<html lang="de">
<header>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"/>
    <link rel="stylesheet" type="text/css" href="rdf.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <script type="application/javascript">
        $(function () {
            var jsTreeJSON = {"core": {"themes": {"dots": false, "stripes": true}}};
            jsTreeJSON['core']['data'] = <?php echo $gebieteData; ?>;
            $("#gebieteTree").jstree(jsTreeJSON);
            jsTreeJSON['core']['data'] = <?php echo $methodenData; ?>;
            $("#methodenTree").jstree(jsTreeJSON);
        })
    </script>
</header>
<body>
<h2>Register</h2>
<div class="treeBox"><h3>Gebiete</h3><div id="gebieteTree"></div></div>
<div class="treeBox"><h3>Methoden</h3><div id="methodenTree"></div></div>
</body>
</html>
