all: createRDFXML

createRDFXML:
	# rapper -g ../Daten/Cube.ttl -o rdfxml-abbrev >rdf/Cube.rdf
	rapper -g ../Daten/MO-AufgabenNachGebieten.ttl -o rdfxml-abbrev >rdf/MO-AufgabenNachGebieten.rdf
	# rapper -g ../Daten/MO-AufgabenTexte.ttl -o rdfxml-abbrev >rdf/MO-AufgabenTexte.rdf
	rapper -g ../Daten/AAG9-Intern.ttl -o rdfxml-abbrev >rdf/AAG9-Intern.rdf
	rapper -g ../Daten/MO-Basisdaten.ttl -o rdfxml-abbrev >rdf/MO-Basisdaten.rdf
